server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      # when running in Docker Compose, Eureka will not be on localhost
      defaultZone: http://eureka:8761/eureka/

spring:
  application:
    name: producer-server